services:
  db:
    container_name: 'mariadb
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/vagrant/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: nextcloud
    image: nextcloud:29.0.2
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /home/vagrant/nextcloud/nextcloud:/var/www/html
      # - /home/vagrant/nextcloud/apps:/var/www/html/custom_apps
      # - /home/vagrant/nextcloud/config:/var/www/html/config
      # - /home/vagrant/nextcloud/data:/var/www/html/data
      # - /home/vagrant/nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db